/*
 * The program takes an XML file as an input and constructs a hashmap with a structure 
 * matching the input XML file elements structure.
 */

import java.io.File;
import java.io.IOException;
import java.util.HashMap;

import org.w3c.dom.*;

import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.ParserConfigurationException;

import org.xml.sax.SAXException;
import org.xml.sax.SAXParseException; 


public class XMLParser
{
	String FileName;//file to parse
	public Document parseXMLFile(String FileName)
	{
		//get the DocumentBuilderfactory
		DocumentBuilderFactory docBuildFactory = DocumentBuilderFactory.newInstance();
		try 
		{
			
			//Using factory get an instance of document builder
			DocumentBuilder docBuilder = docBuildFactory.newDocumentBuilder();

			//parse using builder to get DOM representation of the XML file
			Document dom = docBuilder.parse(FileName);
			return dom;
		}
		catch(ParserConfigurationException pce)
		{
			pce.printStackTrace();
		}
		catch(SAXException se) 
		{
			se.printStackTrace();
		}
		catch(IOException ioe) 
		{
			ioe.printStackTrace();
		}
		return null;
	}
	
	//parseDoc method parses the document generated by parseXMLFile method
	void parseDoc(Element root,HashMap data)
	{
		//Element root = dom.getDocumentElement();  write it in the main method
		if(root == null)
			return;
		NodeList children;
		// Name of the root node in XML file
		String rootName = root.getNodeName();
		if(root.getChildNodes().getLength() > 1)
		{
			children  = root.getChildNodes();
		}
		else
		{
			String text = root.getTextContent();
			data.put(rootName, text);
			return;
			
		}
		
		//root node contains atleast one child , create a HashMap to represent the child content
		HashMap childHashMap = new HashMap();
		data.put(rootName, childHashMap);
		
		for(int i=0;i<children.getLength();i++)
		{
			Node tempNode = children.item(i);
			if(tempNode.getNodeType()==Node.ELEMENT_NODE)
			{
				Element temp = (Element)tempNode;
				parseDoc(temp,childHashMap);
			}
		}
		
	}
	public static void main(String args[])
	{
		XMLParser parser = new XMLParser();
		Document dom = parser.parseXMLFile("/home/chaitanya/Desktop/css.xml");
		dom.getDocumentElement().normalize();
		HashMap<String,Object> data = new HashMap<String,Object>();
		Element root = dom.getDocumentElement(); 
		parser.parseDoc(root, data);
		
		System.out.println("HashMap of the file"+ data.toString());

		
	}


}
